const roles = ['superAdmin', 'admin', 'moderator', 'regular', 'guest'];

const permissions = [
  'ARCHIVE_ADMIN_USER',
  'ARCHIVE_MODERATOR_USER',
  'ARCHIVE_REGULAR_USER',
  'VIEW_ALL_DRAFT_BLOG',
  'VIEW_ALL_ARCHIVED_BLOG',
  'VIEW_ALL_PUBLISHED_BLOG',
  'VIEW_OWN_PUBLISHED_BLOG',
  'EDIT_OWN_DRAFTED_BLOG',
  'EDIT_OWN_PUBLISHED_BLOG',
  'DRAFT_OWN_BLOG',
  'ARCHIVE_OWN_BLOG',
  'ARCHIVE_OTHER_BLOG',
  'PUBLISH_OWN_BLOG',
  'CREATE_ADMIN_USER',
  'CREATE_MODERATOR_USER',
  'CREATE_REGULAR_USER',
  'UPDATE_ALL_USER_ROLE'
];

const superAdmin = [
  'ARCHIVE_ADMIN_USER',
  'ARCHIVE_MODERATOR_USER',
  'ARCHIVE_REGULAR_USER',
  'VIEW_ALL_DRAFT_BLOG',
  'VIEW_ALL_ARCHIVED_BLOG',
  'VIEW_ALL_PUBLISHED_BLOG',
  'VIEW_OWN_PUBLISHED_BLOG',
  'EDIT_OWN_DRAFTED_BLOG',
  'EDIT_OWN_PUBLISHED_BLOG',
  'DRAFT_OWN_BLOG',
  'ARCHIVE_OWN_BLOG',
  'ARCHIVE_OTHER_BLOG',
  'PUBLISH_OWN_BLOG',
  'CREATE_ADMIN_USER',
  'CREATE_MODERATOR_USER',
  'CREATE_REGULAR_USER',
  'UPDATE_ALL_USER_ROLE'
];

const admin = [
  'ARCHIVE_MODERATOR_USER',
  'ARCHIVE_REGULAR_USER',
  'VIEW_ALL_DRAFT_BLOG',
  'VIEW_ALL_ARCHIVED_BLOG',
  'VIEW_ALL_PUBLISHED_BLOG',
  'VIEW_OWN_PUBLISHED_BLOG',
  'EDIT_OWN_DRAFTED_BLOG',
  'EDIT_OWN_PUBLISHED_BLOG',
  'DRAFT_OWN_BLOG',
  'ARCHIVE_OWN_BLOG',
  'ARCHIVE_OTHER_BLOG',
  'PUBLISH_OWN_BLOG',
  'CREATE_MODERATOR_USER',
  'CREATE_REGULAR_USER',
  'UPDATE_USER_ROLE'
];
const moderator = [
  'VIEW_ALL_PUBLISHED_BLOG',
  'VIEW_OWN_PUBLISHED_BLOG',
  'EDIT_OWN_DRAFTED_BLOG',
  'EDIT_OWN_PUBLISHED_BLOG',
  'DRAFT_OWN_BLOG',
  'ARCHIVE_OWN_BLOG',
  'ARCHIVE_OTHER_BLOG',
  'PUBLISH_OWN_BLOG',
];
const regular = [
  'VIEW_ALL_PUBLISHED_BLOG',
  'VIEW_OWN_PUBLISHED_BLOG',
  'EDIT_OWN_DRAFTED_BLOG',
  'EDIT_OWN_PUBLISHED_BLOG',
  'DRAFT_OWN_BLOG',
  'ARCHIVE_OWN_BLOG',
  'PUBLISH_OWN_BLOG',
];

const guest = [
  'VIEW_ALL_PUBLISHED_BLOG',
];

export default {
  roles,
  permissions,
  superAdmin,
  admin,
  moderator,
  regular,
  guest
};
